server:
  port: 8082
spring:
  application:
    name: fitactivity-service
  data:
   mongodb:
    database: fitnessactivity
    uri: mongodb://localhost:27017/fitnessactivity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
