server:
    port: 8084

spring:
  application:
         name: ai-service
  data:
        mongodb:
         database: fitnessrecommendation
         uri: mongodb://localhost:27017/fitnessrecommendation
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    