server:
    port: 8084

spring:
  application:
         name: ai-service
  data:
        mongodb:
         database: fitnessrecommendation
         uri: mongodb://localhost:27017/fitnessrecommendation
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost
      prefer-ip-address: false
rabbitmq:
  exchange: 
    name: fitactivity-exchange
  routing: 
    key: fitactivity-routingkey
  queue: 
    name: fitactivity-queue
gemini:
  api:
    url:${GEMINI_API_URL}
    key:${GEMINI_API_KEY}
    